import { GoogleGenAI } from "@google/genai";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API_KEY environment variable is not set");
  }
  return new GoogleGenAI({ apiKey });
};

export const editImageWithGemini = async (
  base64Image: string,
  prompt: string
): Promise<string> => {
  try {
    const ai = getClient();
    
    // Clean base64 string if it contains data URL prefix
    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");
    
    // Using gemini-2.5-flash-image (Nano Banana) for image editing
    const modelId = "gemini-2.5-flash-image";

    const response = await ai.models.generateContent({
      model: modelId,
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: "image/png", // Assuming PNG for simplicity/compatibility
            },
          },
          {
            text: prompt || "Enhance this image",
          },
        ],
      },
    });

    let generatedImageUrl = "";

    // Iterate through parts to find the image
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          generatedImageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break; // Found the image
        }
      }
    }

    if (!generatedImageUrl) {
       // Fallback if the model returns text instead of an image (e.g. error or refusal)
       const textPart = response.candidates?.[0]?.content?.parts?.find(p => p.text);
       if (textPart?.text) {
         throw new Error(`Model returned text instead of image: ${textPart.text}`);
       }
       throw new Error("No image generated by the model.");
    }

    return generatedImageUrl;
  } catch (error) {
    console.error("Gemini Image Edit Error:", error);
    throw error;
  }
};